version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
    networks:
      - netflix_network

  movie-catalog:
    image: 700935310038.dkr.ecr.us-east-1.amazonaws.com/ai-tsadok/netflix-catalog:latest
    expose:
      - "8080"
    networks:
      - netflix_network

  frontend:
    image: 700935310038.dkr.ecr.us-east-1.amazonaws.com/ai-tsadok/netflix-frontend:latest
    environment:
      - MOVIE_CATALOG_SERVICE=http://movie-catalog:8080
    expose:
      - "3000"
    depends_on:
      - movie-catalog
    networks:
      - netflix_network

networks:
  netflix_network:
    driver: bridge